### PR TITLE
Added wishes ejs. Added wishes routes. Added check for logged in user…

### PR DESCRIPTION
**Pull request by rueda10**
Guys, in this commit I did:

- Added wishes ejs.
- Added wishes routes.
- Added check in footer.ejs for logged in user, and rendering different footer depending on that.
- Moved all javascript code in script tags to login.js. 
- Moved all styling to css file. 
- Removed javascript libraries like slider and holder and added their CDNs instead (they might be too heavy and we might have issues when deploying). 
- Cleaned up style.css and login.js. Added comments and added indentation. 
- Made some tweaks to landing's styling.

### CODE REVIEW

**Review by kimjaydot — COMMENTED** [review]
looks good

**Comment by hhester21** [comment]
looks good!

**Review by hhester21 — APPROVED** [review]

**Review by kimjaydot — APPROVED** [review]
looks goods

**Comment by hhester21** [comment]
shit
I think I hit the wrong thing

**Comment by kimjaydot** [comment]
lol

**Pull request merged**
